### PR TITLE
Adjusted README to new AutomationHub requirements

### PR DESCRIPTION
**Pull request by andy-maier**
The layout follows the [README.md file from the z/OS core collection](https://github.com/ansible-collections/ibm_zos_core/blob/staging-v1.10.0-release-tasks/README.md)

Link to the rendered versions
* README.md: https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/new-readme-content/README.md
* Support matrix: https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/new-readme-content/docs/source/installation.rst#support-matrix

### CODE REVIEW

**Review by anilak11 — APPROVED** [review]
Looks good to me

**Comment by andy-maier** [comment]
Discussion in the team: We will continue using our current approach for service, where we only service the directly preceding minor release.

**Comment by andy-maier** [comment]
I updated the PR to change the statement about support according to the discussion result.
Added two steps in the instructions for releasing a version, for updating the support matrix and the change log table.

**Comment by andy-maier** [comment]
Applied resolution to review comments by Demetrios.

**Comment by andy-maier** [comment]
Keeping the PR open for a while until Haley had a chance to look at the support matrix.

**Comment by andy-maier** [comment]
So far there were no further comments on the PR. I'll merge it and then we can still make changes if needed.

**Pull request merged**
