### PR TITLE
Update document structure with Sphinx theme to allign with Ansible Galaxy suggested format

### PR DESCRIPTION
**Pull request by vkathir82**
Signed-off-by: Kathiravan Velusamy <kathir.velu@in.ibm.com>

Hi Andy & Adilet, 

Below comments for the https://github.com/zhmcclient/zhmc-ansible-modules/pull/157 are addressed now,

1. This should be adjusted to delegating to the docs Makefile, so it works again from the main directory.

**"make docs" works from main directory now.**

2. The commit message fails the gitcop check. Please fix.

**Done**

3. docs/templates/module.rst.j2  This file looks completele different compared to what you have shown in the meeting today. PLease double check whether this is really the file you wanted to have here.

 **I have removed this file template support for now as it still needs to be adjusted for our documentation.**

4.I suggest to remove this batch file. We should be working through the Makefile.

**Done**

5. The ansible-doc-extractor package should be added to the dev-requirements.txt file.

**Added in both dev-requirements.txt and minimum-constraints.txt files**

6.The build of the docs using the Makefile in the docs directory has many warnings, but I'm ok with fixing this in a separate PR.

**I will work with separate PR**

7. It is not clear how the rst files of the zhmc modules can be re-generated (and I always have a bad feeling when generated files are checked in to the repo). How is that done? Also, make html does not re-generate the rst files of the zhmc modules after deleting them manually.

**Actually ansible-doc-extractor reads the *.py from plugins/modules and extracts into *.rst. This a vary powerful feature, as it reduces the need to maintain docs in two places. We can use  "make html" to generate the HTML files from it. e.g. Go to docs directory and run as below, 

_$ ansible-doc-extractor source/modules ../plugins/modules/zhmc_cpc.py
$ make html
$ firefox build/html/index.html (open the HTML file in your browser)_

But now I have changed main directory "make docs" generate both rst and html files**

### CODE REVIEW

**Review by andy-maier — CHANGES_REQUESTED** [review]
Update: Deleted my original posting, since I was using the master branch by accident.

**Review by andy-maier — CHANGES_REQUESTED** [review]
Some comments:

1. The following files were previously either copied from Ansible or generated by the plugin_formatter tool. They have now been moved to the docs/source directory which means we need to maintain them. Is there a better way of doing that? This is a discussion point for our meeting.
    ```
    docs/gen/list_of_all_modules.rst
    docs/gen/modules_support.rst
    docs/gen/common_return_values.rst
    ```

2. In the Makefile, there are these lines:
    ```
    # Location of local clone of Ansible project's Git repository, with the
    # 'devel' branch checked out. Create that with:
    # git clone https://github.com/ansible/ansible.git --branch devel ../ansible
    ansible_repo_dir := ../ansible
    ```
    Since there is a target `$(ansible_repo_dir)` which performs that cloning automatically, the comment should be changed to say something like this:
    ```
    # Location of local clone of Ansible project's Git repository, with the
    # 'devel' branch checked out. Will be cloned automatically.
    ansible_repo_dir := ../ansible
    ```

3. In the Makefile, the rule for cloning the ansible repo uses an incorrect branch `v2.9.12`, which should be changed to `devel`:
    ```
    $(ansible_repo_dir):
    	@echo 'Cloning Ansible repo into: $@'
    	git clone https://github.com/ansible/ansible.git --branch devel $@
    ```

4. Since the `docs/Makefile` is so small now, and since it repeats a number of directory locations from the main `Makefile`, should we not re-integrate these commands into the main Makefile?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9be788e1a8a24e895788ed2f83f264e7cb43fd5
  * Your subject line is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9be788e1a8a24e895788ed2f83f264e7cb43fd5
  * Your subject line is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9be788e1a8a24e895788ed2f83f264e7cb43fd5
  * Your subject line is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9be788e1a8a24e895788ed2f83f264e7cb43fd5
  * Your subject line is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by andy-maier** [comment]
@vkathir82 Kathir, my updates have now fixed the issues on py27 and py35.
I will spend some time on restructuring the RETURN strings in order to address the sanity check issues.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9be788e1a8a24e895788ed2f83f264e7cb43fd5
  * Your subject line is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9be788e1a8a24e895788ed2f83f264e7cb43fd5
  * Your subject line is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9be788e1a8a24e895788ed2f83f264e7cb43fd5
  * Your subject line is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Review by andy-maier — APPROVED** [review]

**Pull request merged**
