### PR TITLE
Improved module documentation

### PR DESCRIPTION
**Pull request by andy-maier**
For details, see the commit message.

### CODE REVIEW

**Comment by andy-maier** [comment]
I plan to update this one once PR #139 is merged.

**Comment by andy-maier** [comment]
Has been rebased on top of PR #139.

**Comment by andy-maier** [comment]
Has been rebased on master, after merging PR #139.
Ready for review.

**Review by vkathir82 — APPROVED** [review]
Hi Andy, Changes related to Z system and other operations are looking good to me

**Pull request merged**
