### PR TITLE
Added support for crypto attachment to partition

### PR DESCRIPTION
**Pull request by andy-maier**
Ready for review.

### CODE REVIEW

**Comment by andy-maier** [comment]
Rebased on master; no other changes so far.
TODO: Work on Andreas's comment.

**Comment by scheuran** [comment]
After our discussion today, we might need to reconsider the output I proposed. I guess the crypto-numbers are the same for control and usage, right?

**Comment by andy-maier** [comment]
On formatting the domain index numbers:

Would an approach of using the format filter help?

The basic pattern is like this:
```
  - name: Show integer formatting using the format filter
    debug:
      msg: "{{ 'int = %s, Formatted int = %02d'|format(item,item|int) }}"
    with_sequence: count=5
```

which results in:
```
ok: [127.0.0.1] => (item=1) => {
    "msg": "int = 1, Formatted int = 01"
}
ok: [127.0.0.1] => (item=2) => {
    "msg": "int = 2, Formatted int = 02"
}
ok: [127.0.0.1] => (item=3) => {
    "msg": "int = 3, Formatted int = 03"
}
ok: [127.0.0.1] => (item=4) => {
    "msg": "int = 4, Formatted int = 04"
}
ok: [127.0.0.1] => (item=5) => {
    "msg": "int = 5, Formatted int = 05"
}
```

This could be used to format domain index numbers from the currently implemented result like this:
```
  - name: Get facts about crypto config of partition 1
    zhmc_crypto_attachment:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      partition_name: "{{ partition_name }}"
      state: facts
    register: result

  - name: Show formatting of domain index numbers of partition 1
    debug:
      msg: "{{ 'domain %02d: mode %s'|format(item.key|int,item.value) }}"
    with_dict: "{{ result.crypto_configuration[partition_name].domains }}"
```
which may result in:
```
ok: [127.0.0.1] => (item={'value': u'control', 'key': u'0'}) => {
    "msg": "domain 00: mode control"
}
ok: [127.0.0.1] => (item={'value': u'control', 'key': u'1'}) => {
    "msg": "domain 01: mode control"
}
```

Using this kind of formatting would allow to add only the "inverted" crypto config, but without the formatted variant, e.g.
```
  control_domains: [0, 1, 2, 3, ...]
  usage_domains: [0, 1, 2, 3, ...]
```

**Comment by andy-maier** [comment]
The last commit changes the result as follows:

* It adds the "inverted" crypto config:
  ```
    "control_domains": [0, 1, 2, 3, ...]
    "usage_domains": [0, 1, 2, 3, ...]
  ```
* It renames the "domains" result key to "domain_config"
* It changes the "adapters" result key to be a dict of adapter names / adapter properties:
  ```
    "adapters": {
      "EP11 0118 A14B-09": {
        "adapter-family": "crypto", 
        "adapter-id": "118", 
        "card-location": "A14B-LG09", 
        "class": "adapter", 
        "crypto-number": 0, 
        "crypto-type": "ep11-coprocessor", 
        "description": "", 
        "detected-card-type": "crypto-express-6s", 
        "name": "EP11 0118 A14B-09", 
        "object-id": "f94633e2-dd28-11e8-8414-00106f236b99", 
        "object-uri": "/api/adapters/f94633e2-dd28-11e8-8414-00106f236b99", 
        "parent": "/api/cpcs/a68c5138-3f41-3060-a285-9ba456518d71", 
        "physical-channel-status": "stopped", 
        "state": "stand-by", 
        "status": "not-active", 
        "tke-commands-enabled": null, 
        "type": "crypto", 
        "udx-loaded": null
      },
      . . .
    }
```

**Comment by andy-maier** [comment]
To answer the question about the use of the partition name as a key in the result: For command-line usage I found it convenient to have the partition name shown in the result, without having to turn on debug to show the input. But I have no strong opinion on this.

**Comment by andy-maier** [comment]
Please try out the latest version in this PR and let me know any remaining comments.

**Comment by andy-maier** [comment]
After getting initial positive feedback from @scheuran , I am merging this PR.

**Pull request merged**
