### PR TITLE
Cleaned up the Makefile

### PR DESCRIPTION
**Pull request by andy-maier**
See commit message.

### CODE REVIEW

**Review by vkathir82 — CHANGES_REQUESTED** [review]
Hi Andy,
The command  make check is failing in all the CI variations and need the fix.

_make: *** No rule to make target 'check'.  Stop.
The command "make check" exited with 2._

**Comment by andy-maier** [comment]
On the 'make check' issue: DONE

**Comment by andy-maier** [comment]
Hi Kathir, are you otherwise ok with the PR, i.e. specifically that the sanity test is now run locally and not using docker?

**Comment by vkathir82** [comment]
Hi Andy, I missed to set "update_needed" for my last comment.

**Comment by andy-maier** [comment]
* Fixed the issue with yaml depenency during yetup by parsing the version with regular expressions.
* Fixed the issue with missing ansible-doc-extractor command by changing the dependencies such that install depends on develop.
* Fixed an issue that showed up locally by adding the missing "rstcheck" Python package.

**Comment by andy-maier** [comment]
Finally this seems to pass. There were several little changes needed for versions of dependencies.

**Pull request merged**
